name: flutter_webshell
description: "Flutter module for embedding Web shell (InAppWebView) into native app."
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0" # 与所选 Flutter 版本匹配（若要兼容 API19，请选仍支持 19 的 Flutter 版本）

dependencies:
  flutter:
    sdk: flutter
  # 建议先用此版本验证；若与你本机/CI Flutter 版本不匹配，可再按需调整
flutter_inappwebview: ^6.1.5  # Or latest from pub.dev

flutter:
  uses-material-design: true
