# 在现有 workflow 的 Build (assembleRelease) 步骤之后加入一个 Rename 步骤并调整 Upload 路径
- name: Rename APK to szmjtvwebapp.apk
  run: |
    mkdir -p artifacts
    # 找到生成的 APK（支持不同的输出名），并复制为所需名字
    find app/build/outputs/apk/release -maxdepth 1 -type f -name "*.apk" -print -quit | while read -r src; do
      echo "Renaming $src -> artifacts/szmjtvwebapp.apk"
      cp "$src" artifacts/szmjtvwebapp.apk
    done

- name: Upload APK artifact (named szmjtvwebapp)
  uses: actions/upload-artifact@v4
  with:
    name: szmjtvwebapp
    path: artifacts/szmjtvwebapp.apk
