name: Android CI - build release APK

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:
    inputs:
      source_url:
        description: 'Homepage URL to fetch'
        required: false
        default: 'https://szzdmj.github.io/index.html'
      base_url:
        description: 'Base URL to fetch webjs.js and sw.js'
        required: false
        default: 'https://szzdmj.github.io/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      - name: Prepare Flutter module (.android) and SDK path
        shell: bash
        run: |
          set -euo pipefail
          flutter --version

          # 通过已安装的 flutter 可执行反推出 SDK 根目录（.../bin/flutter 的上一级）
          FLUTTER_SDK="$(dirname "$(dirname "$(command -v flutter)")")"
          echo "Detected FLUTTER_SDK=${FLUTTER_SDK}"

          # 1) 在项目根写入 local.properties（include_flutter.groovy 会读取这里的 flutter.sdk）
          echo "flutter.sdk=${FLUTTER_SDK}" >> local.properties
          echo "Wrote flutter.sdk to $(pwd)/local.properties"
          tail -n +1 local.properties || true

          # 2) 在 module 内：如不是 module，就就地初始化为 module；随后 pub get + build aar 生成 .android
          cd flutter_webshell
          if [ ! -f .metadata ] || ! grep -q 'project_type: module' .metadata; then
            echo "flutter_webshell is not a Flutter module; initializing as module..."
            flutter create -t module .
          else
            echo "Detected Flutter module."
          fi
          flutter pub get
          # 某些 Flutter 版本仅 pub get 不会生成 .android，执行 build aar 来生成
          flutter build aar
          # 双保险：在 module 目录也写入 flutter.sdk
          echo "flutter.sdk=${FLUTTER_SDK}" >> local.properties

          # 3) 确认 .android 与 include_flutter.groovy
          ls -la .android || (echo ".android not generated" && exit 1)
          test -f .android/include_flutter.groovy || (echo "include_flutter.groovy missing" && exit 1)
          cd ..

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare assets — download only index.html, webjs.js, sw.js (latest)
        env:
          SOURCE_URL: ${{ github.event.inputs.source_url || 'https://szzdmj.github.io/index.html' }}
          BASE_URL: ${{ github.event.inputs.base_url || 'https://szzdmj.github.io/' }}
        run: |
          set -euo pipefail
          mkdir -p app/src/main/assets
          echo "Downloading index.html from ${SOURCE_URL}"
          curl -fsSL -o app/src/main/assets/index.html "${SOURCE_URL}"
          sed -i '1s/^\xEF\xBB\xBF//' app/src/main/assets/index.html || true
          for f in webjs.js sw.js; do
            url="${BASE_URL%/}/${f}"
            dest="app/src/main/assets/${f}"
            echo "Fetching ${url} -> ${dest}"
            curl -fsSL -o "${dest}" "${url}"
          done
          echo "Assets:"
          ls -l app/src/main/assets

      - name: Build (assembleRelease)
        run: ./gradlew assembleRelease --no-daemon
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

      - name: Rename APK to szmjtvwebapp.apk
        run: |
          mkdir -p artifacts
          find app/build/outputs/apk/release -maxdepth 1 -type f -name "*.apk" -print -quit | while read -r src; do
            echo "Renaming $src -> artifacts/szmjtvwebapp.apk"
            cp "$src" artifacts/szmjtvwebapp.apk
          done
          ls -lh artifacts

      - name: Upload APK artifact (named szmjtvwebapp)
        uses: actions/upload-artifact@v4
        with:
          name: szmjtvwebapp
          path: artifacts/szmjtvwebapp.apk
